### PR TITLE
[PIE-1940] Centre editor icons in safari

### PR DESCRIPTION
**Pull request by luke-j**
This adds a simple `flex: '1'` to centre icons in safari. It also pushes a new build.

### CODE REVIEW

**Comment by luke-j** [comment]
@JeanMarcGoepfert Yep sorry forgot to mention that in the PR description, this also captures https://github.com/flippa/react-rte/commit/c179cf104cb762f3d67d238f041e660511e636f4. Having a look, though, that doesn't seem to cover all of the changes in the dist. Possibly a change in the way it's being compiled by packages?

**Comment by luke-j** [comment]
@JeanMarcGoepfert Just double checked this locally and found a warning I hadn't seen earlier. Putting this to WIP until I figure it out.

**Comment by luke-j** [comment]
@JeanMarcGoepfert I've resolved the issue I mentioned before, there will be an error with flippa-ui until https://github.com/flippa/flippa-ui/pull/139 is merged to go along with this PR.

**Comment by luke-j** [comment]
@JeanMarcGoepfert scratch that, more problems. WIP again.

**Comment by luke-j** [comment]
@JeanMarcGoepfert I realised simply rebuilding master (with no code changes) changes ~100ish lines of code in the bundled file. I've just manually made the change to the bundle in this PR to avoid any problems those changes might bring.

We will definitely need to sort this thing out soon.

**Comment by JeanMarcGoepfert** [comment]
@luke-j This is a bit terrifying. I'll try and make time to look into this sometime this week. If we can't find a solution promptly I guess we can ship this and put in an urgent card for tech debt. If we're doing this we should probably put in a big warning in the README not to rebuild this :/

**Comment by luke-j** [comment]
Closing this in favour of removing `react-rte`

**Pull request closed without merging**
